[2022-12-12 18:25:31,361] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: prepare_data.transfer_data scheduled__2022-11-28T16:54:00+00:00 [queued]>
[2022-12-12 18:25:31,640] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: prepare_data.transfer_data scheduled__2022-11-28T16:54:00+00:00 [queued]>
[2022-12-12 18:25:31,642] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2022-12-12 18:25:31,660] {taskinstance.py:1357} INFO - Starting attempt 1 of 1
[2022-12-12 18:25:31,662] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2022-12-12 18:25:32,151] {taskinstance.py:1377} INFO - Executing <Task(PythonOperator): transfer_data> on 2022-11-28 16:54:00+00:00
[2022-12-12 18:25:32,223] {standard_task_runner.py:52} INFO - Started process 358 to run task
[2022-12-12 18:25:32,221] {standard_task_runner.py:79} INFO - Running: ['airflow', 'tasks', 'run', 'prepare_data', 'transfer_data', 'scheduled__2022-11-28T16:54:00+00:00', '--job-id', '74', '--raw', '--subdir', 'DAGS_FOLDER/prepare_data.py', '--cfg-path', '/tmp/tmpmlbyb6mr', '--error-file', '/tmp/tmpb4sauq7e']
[2022-12-12 18:25:32,239] {standard_task_runner.py:80} INFO - Job 74: Subtask transfer_data
[2022-12-12 18:25:32,539] {task_command.py:369} INFO - Running <TaskInstance: prepare_data.transfer_data scheduled__2022-11-28T16:54:00+00:00 [running]> on host a49e44ee4a94
[2022-12-12 18:25:33,706] {taskinstance.py:1571} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=prepare_data
AIRFLOW_CTX_TASK_ID=transfer_data
AIRFLOW_CTX_EXECUTION_DATE=2022-11-28T16:54:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2022-11-28T16:54:00+00:00
[2022-12-12 18:25:33,774] {base.py:68} INFO - Using connection ID 'postgres_default' for task execution.
[2022-12-12 18:25:33,913] {python.py:173} INFO - Done. Returned value was: None
[2022-12-12 18:25:34,125] {taskinstance.py:1400} INFO - Marking task as SUCCESS. dag_id=prepare_data, task_id=transfer_data, execution_date=20221128T165400, start_date=20221212T182531, end_date=20221212T182534
[2022-12-12 18:25:34,531] {local_task_job.py:156} INFO - Task exited with return code 0
[2022-12-12 18:25:34,790] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2022-12-12 18:38:44,518] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: prepare_data.transfer_data scheduled__2022-11-28T16:54:00+00:00 [queued]>
[2022-12-12 18:38:44,564] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: prepare_data.transfer_data scheduled__2022-11-28T16:54:00+00:00 [queued]>
[2022-12-12 18:38:44,566] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2022-12-12 18:38:44,568] {taskinstance.py:1357} INFO - Starting attempt 1 of 1
[2022-12-12 18:38:44,570] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2022-12-12 18:38:44,610] {taskinstance.py:1377} INFO - Executing <Task(PythonOperator): transfer_data> on 2022-11-28 16:54:00+00:00
[2022-12-12 18:38:44,620] {standard_task_runner.py:52} INFO - Started process 295 to run task
[2022-12-12 18:38:44,631] {standard_task_runner.py:79} INFO - Running: ['airflow', 'tasks', 'run', 'prepare_data', 'transfer_data', 'scheduled__2022-11-28T16:54:00+00:00', '--job-id', '48', '--raw', '--subdir', 'DAGS_FOLDER/prepare_data.py', '--cfg-path', '/tmp/tmpy6mrrdee', '--error-file', '/tmp/tmpw2iu2di_']
[2022-12-12 18:38:44,634] {standard_task_runner.py:80} INFO - Job 48: Subtask transfer_data
[2022-12-12 18:38:44,837] {task_command.py:369} INFO - Running <TaskInstance: prepare_data.transfer_data scheduled__2022-11-28T16:54:00+00:00 [running]> on host cfea470654c7
[2022-12-12 18:38:45,013] {taskinstance.py:1571} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=prepare_data
AIRFLOW_CTX_TASK_ID=transfer_data
AIRFLOW_CTX_EXECUTION_DATE=2022-11-28T16:54:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2022-11-28T16:54:00+00:00
[2022-12-12 18:38:45,036] {base.py:68} INFO - Using connection ID 'postgres_default' for task execution.
[2022-12-12 18:38:45,071] {python.py:173} INFO - Done. Returned value was: None
[2022-12-12 18:38:45,116] {taskinstance.py:1400} INFO - Marking task as SUCCESS. dag_id=prepare_data, task_id=transfer_data, execution_date=20221128T165400, start_date=20221212T183844, end_date=20221212T183845
[2022-12-12 18:38:45,208] {local_task_job.py:156} INFO - Task exited with return code 0
[2022-12-12 18:38:45,679] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
