[2022-12-16 08:18:41,721] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: prepare_data.create_table scheduled__2022-12-15T17:54:00+00:00 [queued]>
[2022-12-16 08:18:42,034] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: prepare_data.create_table scheduled__2022-12-15T17:54:00+00:00 [queued]>
[2022-12-16 08:18:42,034] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2022-12-16 08:18:42,034] {taskinstance.py:1357} INFO - Starting attempt 1 of 1
[2022-12-16 08:18:42,035] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2022-12-16 08:18:42,741] {taskinstance.py:1377} INFO - Executing <Task(PostgresOperator): create_table> on 2022-12-15 17:54:00+00:00
[2022-12-16 08:18:42,784] {standard_task_runner.py:52} INFO - Started process 17070 to run task
[2022-12-16 08:18:42,923] {standard_task_runner.py:79} INFO - Running: ['airflow', 'tasks', 'run', 'prepare_data', 'create_table', 'scheduled__2022-12-15T17:54:00+00:00', '--job-id', '211', '--raw', '--subdir', 'DAGS_FOLDER/prepare_data.py', '--cfg-path', '/tmp/tmp_1m8h9_n', '--error-file', '/tmp/tmpk6_ppjle']
[2022-12-16 08:18:43,016] {standard_task_runner.py:80} INFO - Job 211: Subtask create_table
[2022-12-16 08:18:44,625] {task_command.py:369} INFO - Running <TaskInstance: prepare_data.create_table scheduled__2022-12-15T17:54:00+00:00 [running]> on host 8e2f65ec4c74
[2022-12-16 08:18:46,747] {taskinstance.py:1571} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=prepare_data
AIRFLOW_CTX_TASK_ID=create_table
AIRFLOW_CTX_EXECUTION_DATE=2022-12-15T17:54:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2022-12-15T17:54:00+00:00
[2022-12-16 08:18:47,049] {base.py:68} INFO - Using connection ID 'gp_conn' for task execution.
[2022-12-16 08:18:47,204] {dbapi.py:208} INFO - Running statement: CREATE TABLE IF NOT EXISTS prepared_data (
	id SERIAL,
	sensor_id BIGINT,
	longitude FLOAT,
	latitude FLOAT,
	controller_id BIGINT,
	datetime TIMESTAMP WITH TIME ZONE,
	temperature INTEGER
);, parameters: None
[2022-12-16 08:18:47,225] {postgres.py:94} INFO - NOTICE:  relation "prepared_data" already exists, skipping

[2022-12-16 08:18:47,395] {taskinstance.py:1400} INFO - Marking task as SUCCESS. dag_id=prepare_data, task_id=create_table, execution_date=20221215T175400, start_date=20221216T081841, end_date=20221216T081847
[2022-12-16 08:18:47,621] {local_task_job.py:156} INFO - Task exited with return code 0
[2022-12-16 08:18:48,898] {local_task_job.py:273} INFO - 1 downstream tasks scheduled from follow-on schedule check
