[2022-12-12 18:25:47,681] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: prepare_data.get_last_id scheduled__2022-11-28T17:06:00+00:00 [queued]>
[2022-12-12 18:25:47,954] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: prepare_data.get_last_id scheduled__2022-11-28T17:06:00+00:00 [queued]>
[2022-12-12 18:25:47,968] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2022-12-12 18:25:47,979] {taskinstance.py:1357} INFO - Starting attempt 1 of 1
[2022-12-12 18:25:47,984] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2022-12-12 18:25:48,370] {taskinstance.py:1377} INFO - Executing <Task(PythonOperator): get_last_id> on 2022-11-28 17:06:00+00:00
[2022-12-12 18:25:48,413] {standard_task_runner.py:52} INFO - Started process 412 to run task
[2022-12-12 18:25:48,452] {standard_task_runner.py:79} INFO - Running: ['airflow', 'tasks', 'run', 'prepare_data', 'get_last_id', 'scheduled__2022-11-28T17:06:00+00:00', '--job-id', '99', '--raw', '--subdir', 'DAGS_FOLDER/prepare_data.py', '--cfg-path', '/tmp/tmp4tpsq0rg', '--error-file', '/tmp/tmpy2t3ctx2']
[2022-12-12 18:25:48,467] {standard_task_runner.py:80} INFO - Job 99: Subtask get_last_id
[2022-12-12 18:25:49,003] {task_command.py:369} INFO - Running <TaskInstance: prepare_data.get_last_id scheduled__2022-11-28T17:06:00+00:00 [running]> on host a49e44ee4a94
[2022-12-12 18:25:49,985] {taskinstance.py:1571} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=prepare_data
AIRFLOW_CTX_TASK_ID=get_last_id
AIRFLOW_CTX_EXECUTION_DATE=2022-11-28T17:06:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2022-11-28T17:06:00+00:00
[2022-12-12 18:25:50,169] {base.py:68} INFO - Using connection ID 'postgres_default' for task execution.
[2022-12-12 18:25:50,516] {python.py:173} INFO - Done. Returned value was: None
[2022-12-12 18:25:51,070] {taskinstance.py:1400} INFO - Marking task as SUCCESS. dag_id=prepare_data, task_id=get_last_id, execution_date=20221128T170600, start_date=20221212T182547, end_date=20221212T182551
[2022-12-12 18:25:51,273] {local_task_job.py:156} INFO - Task exited with return code 0
[2022-12-12 18:25:51,575] {local_task_job.py:273} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2022-12-12 18:39:03,495] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: prepare_data.get_last_id scheduled__2022-11-28T17:06:00+00:00 [queued]>
[2022-12-12 18:39:03,632] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: prepare_data.get_last_id scheduled__2022-11-28T17:06:00+00:00 [queued]>
[2022-12-12 18:39:03,635] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2022-12-12 18:39:03,640] {taskinstance.py:1357} INFO - Starting attempt 1 of 1
[2022-12-12 18:39:03,643] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2022-12-12 18:39:03,868] {taskinstance.py:1377} INFO - Executing <Task(PythonOperator): get_last_id> on 2022-11-28 17:06:00+00:00
[2022-12-12 18:39:03,982] {standard_task_runner.py:52} INFO - Started process 372 to run task
[2022-12-12 18:39:04,057] {standard_task_runner.py:79} INFO - Running: ['airflow', 'tasks', 'run', 'prepare_data', 'get_last_id', 'scheduled__2022-11-28T17:06:00+00:00', '--job-id', '84', '--raw', '--subdir', 'DAGS_FOLDER/prepare_data.py', '--cfg-path', '/tmp/tmp1zphc1jg', '--error-file', '/tmp/tmpysdmv14g']
[2022-12-12 18:39:04,097] {standard_task_runner.py:80} INFO - Job 84: Subtask get_last_id
[2022-12-12 18:39:05,027] {task_command.py:369} INFO - Running <TaskInstance: prepare_data.get_last_id scheduled__2022-11-28T17:06:00+00:00 [running]> on host cfea470654c7
[2022-12-12 18:39:05,878] {taskinstance.py:1571} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=prepare_data
AIRFLOW_CTX_TASK_ID=get_last_id
AIRFLOW_CTX_EXECUTION_DATE=2022-11-28T17:06:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2022-11-28T17:06:00+00:00
[2022-12-12 18:39:06,051] {base.py:68} INFO - Using connection ID 'postgres_default' for task execution.
[2022-12-12 18:39:06,145] {python.py:173} INFO - Done. Returned value was: None
[2022-12-12 18:39:06,401] {taskinstance.py:1400} INFO - Marking task as SUCCESS. dag_id=prepare_data, task_id=get_last_id, execution_date=20221128T170600, start_date=20221212T183903, end_date=20221212T183906
[2022-12-12 18:39:06,599] {local_task_job.py:156} INFO - Task exited with return code 0
[2022-12-12 18:39:08,264] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
