[2022-12-16 08:08:16,109] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: prepare_data.create_table scheduled__2022-12-15T17:12:00+00:00 [queued]>
[2022-12-16 08:08:18,724] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: prepare_data.create_table scheduled__2022-12-15T17:12:00+00:00 [queued]>
[2022-12-16 08:08:18,888] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2022-12-16 08:08:18,907] {taskinstance.py:1357} INFO - Starting attempt 1 of 1
[2022-12-16 08:08:18,914] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2022-12-16 08:08:25,780] {taskinstance.py:1377} INFO - Executing <Task(PostgresOperator): create_table> on 2022-12-15 17:12:00+00:00
[2022-12-16 08:08:26,362] {standard_task_runner.py:52} INFO - Started process 16756 to run task
[2022-12-16 08:08:31,032] {standard_task_runner.py:79} INFO - Running: ['airflow', 'tasks', 'run', 'prepare_data', 'create_table', 'scheduled__2022-12-15T17:12:00+00:00', '--job-id', '84', '--raw', '--subdir', 'DAGS_FOLDER/prepare_data.py', '--cfg-path', '/tmp/tmp9ea2kvli', '--error-file', '/tmp/tmpzrd1aywj']
[2022-12-16 08:08:31,925] {standard_task_runner.py:80} INFO - Job 84: Subtask create_table
[2022-12-16 08:08:56,437] {task_command.py:369} INFO - Running <TaskInstance: prepare_data.create_table scheduled__2022-12-15T17:12:00+00:00 [running]> on host 8e2f65ec4c74
[2022-12-16 08:09:05,799] {taskinstance.py:1571} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=prepare_data
AIRFLOW_CTX_TASK_ID=create_table
AIRFLOW_CTX_EXECUTION_DATE=2022-12-15T17:12:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2022-12-15T17:12:00+00:00
[2022-12-16 08:09:07,464] {base.py:68} INFO - Using connection ID 'gp_conn' for task execution.
[2022-12-16 08:09:09,365] {dbapi.py:208} INFO - Running statement: CREATE TABLE IF NOT EXISTS prepared_data (
	id SERIAL,
	sensor_id BIGINT,
	longitude FLOAT,
	latitude FLOAT,
	controller_id BIGINT,
	datetime TIMESTAMP WITH TIME ZONE,
	temperature INTEGER
);, parameters: None
[2022-12-16 08:09:09,491] {postgres.py:94} INFO - NOTICE:  relation "prepared_data" already exists, skipping

[2022-12-16 08:09:10,818] {taskinstance.py:1400} INFO - Marking task as SUCCESS. dag_id=prepare_data, task_id=create_table, execution_date=20221215T171200, start_date=20221216T080816, end_date=20221216T080910
[2022-12-16 08:09:12,610] {local_task_job.py:156} INFO - Task exited with return code 0
[2022-12-16 08:09:17,024] {local_task_job.py:273} INFO - 1 downstream tasks scheduled from follow-on schedule check
