[2022-12-16 10:52:55,970] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: prepare_data.get_last_id scheduled__2022-12-16T00:16:00+00:00 [queued]>
[2022-12-16 10:52:56,754] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: prepare_data.get_last_id scheduled__2022-12-16T00:16:00+00:00 [queued]>
[2022-12-16 10:52:56,760] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2022-12-16 10:52:56,795] {taskinstance.py:1357} INFO - Starting attempt 1 of 1
[2022-12-16 10:52:56,799] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2022-12-16 10:52:57,688] {taskinstance.py:1377} INFO - Executing <Task(PythonOperator): get_last_id> on 2022-12-16 00:16:00+00:00
[2022-12-16 10:52:57,787] {standard_task_runner.py:52} INFO - Started process 2663 to run task
[2022-12-16 10:52:57,906] {standard_task_runner.py:79} INFO - Running: ['airflow', 'tasks', 'run', 'prepare_data', 'get_last_id', 'scheduled__2022-12-16T00:16:00+00:00', '--job-id', '1378', '--raw', '--subdir', 'DAGS_FOLDER/prepare_data.py', '--cfg-path', '/tmp/tmp_3epnz2j', '--error-file', '/tmp/tmp1ng3zs14']
[2022-12-16 10:52:57,921] {standard_task_runner.py:80} INFO - Job 1378: Subtask get_last_id
[2022-12-16 10:52:59,488] {task_command.py:369} INFO - Running <TaskInstance: prepare_data.get_last_id scheduled__2022-12-16T00:16:00+00:00 [running]> on host 8e2f65ec4c74
[2022-12-16 10:53:01,193] {taskinstance.py:1571} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=prepare_data
AIRFLOW_CTX_TASK_ID=get_last_id
AIRFLOW_CTX_EXECUTION_DATE=2022-12-16T00:16:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2022-12-16T00:16:00+00:00
[2022-12-16 10:53:01,440] {base.py:68} INFO - Using connection ID 'gp_conn' for task execution.
[2022-12-16 10:53:01,664] {python.py:173} INFO - Done. Returned value was: None
[2022-12-16 10:53:03,448] {taskinstance.py:1400} INFO - Marking task as SUCCESS. dag_id=prepare_data, task_id=get_last_id, execution_date=20221216T001600, start_date=20221216T105255, end_date=20221216T105303
[2022-12-16 10:53:04,024] {local_task_job.py:221} WARNING - State of this instance has been externally set to success. Terminating instance.
[2022-12-16 10:53:04,155] {process_utils.py:129} INFO - Sending Signals.SIGTERM to group 2663. PIDs of all processes in the group: [2663]
[2022-12-16 10:53:04,157] {process_utils.py:80} INFO - Sending the signal Signals.SIGTERM to group 2663
[2022-12-16 10:53:04,161] {process_utils.py:75} INFO - Process psutil.Process(pid=2663, status='terminated', exitcode=0, started='10:52:57') (2663) terminated with exit code 0
