[2022-12-16 10:34:27,096] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: prepare_data.create_table scheduled__2022-12-15T19:37:00+00:00 [queued]>
[2022-12-16 10:34:27,339] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: prepare_data.create_table scheduled__2022-12-15T19:37:00+00:00 [queued]>
[2022-12-16 10:34:27,339] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2022-12-16 10:34:27,339] {taskinstance.py:1357} INFO - Starting attempt 1 of 1
[2022-12-16 10:34:27,339] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2022-12-16 10:34:27,791] {taskinstance.py:1377} INFO - Executing <Task(PostgresOperator): create_table> on 2022-12-15 19:37:00+00:00
[2022-12-16 10:34:27,857] {standard_task_runner.py:52} INFO - Started process 804 to run task
[2022-12-16 10:34:27,907] {standard_task_runner.py:79} INFO - Running: ['airflow', 'tasks', 'run', 'prepare_data', 'create_table', 'scheduled__2022-12-15T19:37:00+00:00', '--job-id', '533', '--raw', '--subdir', 'DAGS_FOLDER/prepare_data.py', '--cfg-path', '/tmp/tmpdjdj1k7v', '--error-file', '/tmp/tmpacx19v6i']
[2022-12-16 10:34:27,940] {standard_task_runner.py:80} INFO - Job 533: Subtask create_table
[2022-12-16 10:34:28,749] {task_command.py:369} INFO - Running <TaskInstance: prepare_data.create_table scheduled__2022-12-15T19:37:00+00:00 [running]> on host 8e2f65ec4c74
[2022-12-16 10:34:31,827] {taskinstance.py:1571} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=prepare_data
AIRFLOW_CTX_TASK_ID=create_table
AIRFLOW_CTX_EXECUTION_DATE=2022-12-15T19:37:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2022-12-15T19:37:00+00:00
[2022-12-16 10:34:32,085] {base.py:68} INFO - Using connection ID 'gp_conn' for task execution.
[2022-12-16 10:34:32,165] {dbapi.py:208} INFO - Running statement: CREATE TABLE IF NOT EXISTS prepared_data (
	id SERIAL,
	sensor_id BIGINT,
	longitude FLOAT,
	latitude FLOAT,
	controller_id BIGINT,
	datetime TIMESTAMP WITH TIME ZONE,
	temperature INTEGER
);, parameters: None
[2022-12-16 10:34:32,174] {postgres.py:94} INFO - NOTICE:  relation "prepared_data" already exists, skipping

[2022-12-16 10:34:33,963] {taskinstance.py:1400} INFO - Marking task as SUCCESS. dag_id=prepare_data, task_id=create_table, execution_date=20221215T193700, start_date=20221216T103427, end_date=20221216T103433
[2022-12-16 10:34:34,447] {local_task_job.py:156} INFO - Task exited with return code 0
[2022-12-16 10:34:35,806] {local_task_job.py:273} INFO - 1 downstream tasks scheduled from follow-on schedule check
