[2022-12-16 13:04:55,146] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: prepare_data.create_table scheduled__2022-12-16T12:31:00+00:00 [queued]>
[2022-12-16 13:04:55,266] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: prepare_data.create_table scheduled__2022-12-16T12:31:00+00:00 [queued]>
[2022-12-16 13:04:55,280] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2022-12-16 13:04:55,280] {taskinstance.py:1357} INFO - Starting attempt 1 of 1
[2022-12-16 13:04:55,280] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2022-12-16 13:04:55,439] {taskinstance.py:1377} INFO - Executing <Task(PostgresOperator): create_table> on 2022-12-16 12:31:00+00:00
[2022-12-16 13:04:55,480] {standard_task_runner.py:52} INFO - Started process 4115 to run task
[2022-12-16 13:04:55,535] {standard_task_runner.py:79} INFO - Running: ['airflow', 'tasks', 'run', 'prepare_data', 'create_table', 'scheduled__2022-12-16T12:31:00+00:00', '--job-id', '2033', '--raw', '--subdir', 'DAGS_FOLDER/prepare_data.py', '--cfg-path', '/tmp/tmp8tn85w6l', '--error-file', '/tmp/tmpt61c7z4d']
[2022-12-16 13:04:55,569] {standard_task_runner.py:80} INFO - Job 2033: Subtask create_table
[2022-12-16 13:04:55,957] {task_command.py:369} INFO - Running <TaskInstance: prepare_data.create_table scheduled__2022-12-16T12:31:00+00:00 [running]> on host 8e2f65ec4c74
[2022-12-16 13:04:56,816] {taskinstance.py:1571} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=prepare_data
AIRFLOW_CTX_TASK_ID=create_table
AIRFLOW_CTX_EXECUTION_DATE=2022-12-16T12:31:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2022-12-16T12:31:00+00:00
[2022-12-16 13:04:56,930] {base.py:68} INFO - Using connection ID 'gp_conn' for task execution.
[2022-12-16 13:04:56,978] {dbapi.py:208} INFO - Running statement: CREATE TABLE IF NOT EXISTS prepared_data (
	id SERIAL,
	sensor_id BIGINT,
	longitude FLOAT,
	latitude FLOAT,
	controller_id BIGINT,
	datetime TIMESTAMP WITH TIME ZONE,
	temperature INTEGER
);, parameters: None
[2022-12-16 13:04:56,985] {postgres.py:94} INFO - NOTICE:  relation "prepared_data" already exists, skipping

[2022-12-16 13:04:57,475] {taskinstance.py:1400} INFO - Marking task as SUCCESS. dag_id=prepare_data, task_id=create_table, execution_date=20221216T123100, start_date=20221216T130455, end_date=20221216T130457
[2022-12-16 13:04:57,557] {local_task_job.py:156} INFO - Task exited with return code 0
[2022-12-16 13:04:58,067] {local_task_job.py:273} INFO - 1 downstream tasks scheduled from follow-on schedule check
