[2022-12-12 18:44:00,773] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: prepare_data.get_last_id scheduled__2022-11-28T20:38:00+00:00 [queued]>
[2022-12-12 18:44:00,869] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: prepare_data.get_last_id scheduled__2022-11-28T20:38:00+00:00 [queued]>
[2022-12-12 18:44:00,871] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2022-12-12 18:44:00,872] {taskinstance.py:1357} INFO - Starting attempt 1 of 1
[2022-12-12 18:44:00,875] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2022-12-12 18:44:01,037] {taskinstance.py:1377} INFO - Executing <Task(PythonOperator): get_last_id> on 2022-11-28 20:38:00+00:00
[2022-12-12 18:44:01,085] {standard_task_runner.py:52} INFO - Started process 1696 to run task
[2022-12-12 18:44:01,112] {standard_task_runner.py:79} INFO - Running: ['airflow', 'tasks', 'run', 'prepare_data', 'get_last_id', 'scheduled__2022-11-28T20:38:00+00:00', '--job-id', '722', '--raw', '--subdir', 'DAGS_FOLDER/prepare_data.py', '--cfg-path', '/tmp/tmp2xttqxaf', '--error-file', '/tmp/tmpz094hfzj']
[2022-12-12 18:44:01,122] {standard_task_runner.py:80} INFO - Job 722: Subtask get_last_id
[2022-12-12 18:44:01,977] {task_command.py:369} INFO - Running <TaskInstance: prepare_data.get_last_id scheduled__2022-11-28T20:38:00+00:00 [running]> on host cfea470654c7
[2022-12-12 18:44:03,252] {taskinstance.py:1571} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=prepare_data
AIRFLOW_CTX_TASK_ID=get_last_id
AIRFLOW_CTX_EXECUTION_DATE=2022-11-28T20:38:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2022-11-28T20:38:00+00:00
[2022-12-12 18:44:03,313] {base.py:68} INFO - Using connection ID 'postgres_default' for task execution.
[2022-12-12 18:44:03,505] {python.py:173} INFO - Done. Returned value was: None
[2022-12-12 18:44:03,690] {taskinstance.py:1400} INFO - Marking task as SUCCESS. dag_id=prepare_data, task_id=get_last_id, execution_date=20221128T203800, start_date=20221212T184400, end_date=20221212T184403
[2022-12-12 18:44:04,155] {local_task_job.py:156} INFO - Task exited with return code 0
[2022-12-12 18:44:04,301] {local_task_job.py:84} ERROR - Received SIGTERM. Terminating subprocesses
[2022-12-12 18:44:04,349] {local_task_job.py:156} INFO - Task exited with return code 143
