[2022-12-12 18:25:32,604] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: prepare_data.transfer_data scheduled__2022-11-28T16:55:00+00:00 [queued]>
[2022-12-12 18:25:32,716] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: prepare_data.transfer_data scheduled__2022-11-28T16:55:00+00:00 [queued]>
[2022-12-12 18:25:32,718] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2022-12-12 18:25:32,720] {taskinstance.py:1357} INFO - Starting attempt 1 of 1
[2022-12-12 18:25:32,722] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2022-12-12 18:25:32,994] {taskinstance.py:1377} INFO - Executing <Task(PythonOperator): transfer_data> on 2022-11-28 16:55:00+00:00
[2022-12-12 18:25:33,029] {standard_task_runner.py:52} INFO - Started process 364 to run task
[2022-12-12 18:25:33,278] {standard_task_runner.py:79} INFO - Running: ['airflow', 'tasks', 'run', 'prepare_data', 'transfer_data', 'scheduled__2022-11-28T16:55:00+00:00', '--job-id', '78', '--raw', '--subdir', 'DAGS_FOLDER/prepare_data.py', '--cfg-path', '/tmp/tmpnq65_l_8', '--error-file', '/tmp/tmpdiwexvkz']
[2022-12-12 18:25:33,314] {standard_task_runner.py:80} INFO - Job 78: Subtask transfer_data
[2022-12-12 18:25:34,133] {task_command.py:369} INFO - Running <TaskInstance: prepare_data.transfer_data scheduled__2022-11-28T16:55:00+00:00 [running]> on host a49e44ee4a94
[2022-12-12 18:25:35,083] {taskinstance.py:1571} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=prepare_data
AIRFLOW_CTX_TASK_ID=transfer_data
AIRFLOW_CTX_EXECUTION_DATE=2022-11-28T16:55:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2022-11-28T16:55:00+00:00
[2022-12-12 18:25:35,184] {base.py:68} INFO - Using connection ID 'postgres_default' for task execution.
[2022-12-12 18:25:35,384] {python.py:173} INFO - Done. Returned value was: None
[2022-12-12 18:25:35,769] {taskinstance.py:1400} INFO - Marking task as SUCCESS. dag_id=prepare_data, task_id=transfer_data, execution_date=20221128T165500, start_date=20221212T182532, end_date=20221212T182535
[2022-12-12 18:25:35,953] {local_task_job.py:156} INFO - Task exited with return code 0
[2022-12-12 18:25:36,763] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2022-12-12 18:38:46,202] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: prepare_data.transfer_data scheduled__2022-11-28T16:55:00+00:00 [queued]>
[2022-12-12 18:38:46,224] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: prepare_data.transfer_data scheduled__2022-11-28T16:55:00+00:00 [queued]>
[2022-12-12 18:38:46,228] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2022-12-12 18:38:46,229] {taskinstance.py:1357} INFO - Starting attempt 1 of 1
[2022-12-12 18:38:46,230] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2022-12-12 18:38:46,255] {taskinstance.py:1377} INFO - Executing <Task(PythonOperator): transfer_data> on 2022-11-28 16:55:00+00:00
[2022-12-12 18:38:46,263] {standard_task_runner.py:52} INFO - Started process 299 to run task
[2022-12-12 18:38:46,268] {standard_task_runner.py:79} INFO - Running: ['airflow', 'tasks', 'run', 'prepare_data', 'transfer_data', 'scheduled__2022-11-28T16:55:00+00:00', '--job-id', '51', '--raw', '--subdir', 'DAGS_FOLDER/prepare_data.py', '--cfg-path', '/tmp/tmp53e2622c', '--error-file', '/tmp/tmptvhtrn97']
[2022-12-12 18:38:46,271] {standard_task_runner.py:80} INFO - Job 51: Subtask transfer_data
[2022-12-12 18:38:46,407] {task_command.py:369} INFO - Running <TaskInstance: prepare_data.transfer_data scheduled__2022-11-28T16:55:00+00:00 [running]> on host cfea470654c7
[2022-12-12 18:38:46,573] {taskinstance.py:1571} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=prepare_data
AIRFLOW_CTX_TASK_ID=transfer_data
AIRFLOW_CTX_EXECUTION_DATE=2022-11-28T16:55:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2022-11-28T16:55:00+00:00
[2022-12-12 18:38:46,594] {base.py:68} INFO - Using connection ID 'postgres_default' for task execution.
[2022-12-12 18:38:46,621] {python.py:173} INFO - Done. Returned value was: None
[2022-12-12 18:38:46,644] {taskinstance.py:1400} INFO - Marking task as SUCCESS. dag_id=prepare_data, task_id=transfer_data, execution_date=20221128T165500, start_date=20221212T183846, end_date=20221212T183846
[2022-12-12 18:38:46,685] {local_task_job.py:156} INFO - Task exited with return code 0
[2022-12-12 18:38:46,758] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
