[2022-12-16 08:06:41,241] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: prepare_data.create_table scheduled__2022-12-15T17:08:00+00:00 [queued]>
[2022-12-16 08:06:41,388] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: prepare_data.create_table scheduled__2022-12-15T17:08:00+00:00 [queued]>
[2022-12-16 08:06:41,389] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2022-12-16 08:06:41,402] {taskinstance.py:1357} INFO - Starting attempt 1 of 1
[2022-12-16 08:06:41,403] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2022-12-16 08:06:42,202] {taskinstance.py:1377} INFO - Executing <Task(PostgresOperator): create_table> on 2022-12-15 17:08:00+00:00
[2022-12-16 08:06:42,402] {standard_task_runner.py:52} INFO - Started process 16703 to run task
[2022-12-16 08:06:42,462] {standard_task_runner.py:79} INFO - Running: ['airflow', 'tasks', 'run', 'prepare_data', 'create_table', 'scheduled__2022-12-15T17:08:00+00:00', '--job-id', '65', '--raw', '--subdir', 'DAGS_FOLDER/prepare_data.py', '--cfg-path', '/tmp/tmpkh5r3i7q', '--error-file', '/tmp/tmp9uum71kt']
[2022-12-16 08:06:42,477] {standard_task_runner.py:80} INFO - Job 65: Subtask create_table
[2022-12-16 08:06:44,622] {task_command.py:369} INFO - Running <TaskInstance: prepare_data.create_table scheduled__2022-12-15T17:08:00+00:00 [running]> on host 8e2f65ec4c74
[2022-12-16 08:06:47,711] {taskinstance.py:1571} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=prepare_data
AIRFLOW_CTX_TASK_ID=create_table
AIRFLOW_CTX_EXECUTION_DATE=2022-12-15T17:08:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2022-12-15T17:08:00+00:00
[2022-12-16 08:06:48,391] {base.py:68} INFO - Using connection ID 'gp_conn' for task execution.
[2022-12-16 08:06:48,659] {dbapi.py:208} INFO - Running statement: CREATE TABLE IF NOT EXISTS prepared_data (
	id SERIAL,
	sensor_id BIGINT,
	longitude FLOAT,
	latitude FLOAT,
	controller_id BIGINT,
	datetime TIMESTAMP WITH TIME ZONE,
	temperature INTEGER
);, parameters: None
[2022-12-16 08:06:48,705] {postgres.py:94} INFO - NOTICE:  relation "prepared_data" already exists, skipping

[2022-12-16 08:06:49,260] {taskinstance.py:1400} INFO - Marking task as SUCCESS. dag_id=prepare_data, task_id=create_table, execution_date=20221215T170800, start_date=20221216T080641, end_date=20221216T080649
[2022-12-16 08:06:49,660] {local_task_job.py:156} INFO - Task exited with return code 0
[2022-12-16 08:06:50,819] {local_task_job.py:273} INFO - 1 downstream tasks scheduled from follow-on schedule check
